module-name: compass-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/compass-manager:v20231122-e4b4fa5b
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"