module-name: compass-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/compass-manager:v20231025-d94a34b6
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"