module-name: compass-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/compass-manager:v20231220-64947f89
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
