
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: compass-manager
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: compass-manager-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: compass-manager
    app.kubernetes.io/part-of: compass-manager
    app.kubernetes.io/managed-by: kustomize
  name: compass-manager-metrics-monitor
  namespace: kcp-system
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: compass-manager
