# permissions for end users to view compassmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: compassmanager-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: compass-manager
    app.kubernetes.io/part-of: compass-manager
    app.kubernetes.io/managed-by: kustomize
  name: compassmanager-viewer-role
  namespace: kcp-system
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - compassmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - compassmanagers/status
  verbs:
  - get
