---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: compass-manager-role
  namespace: kcp-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - compassmanagermappings
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - compassmanagermappings/finalizers
  verbs:
  - get
  - update
- apiGroups:
  - operator.kyma-project.io
  resources:
  - compassmanagermappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kymas
  verbs:
  - get
  - list
  - watch
