---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - compassmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - compassmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - operator.kyma-project.io
  resources:
  - compassmanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kymas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kymas/status
  verbs:
  - get
