apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: compass-manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: compass-manager
    app.kubernetes.io/part-of: compass-manager
    app.kubernetes.io/managed-by: kustomize
  name: compass-manager-rolebinding
  namespace: kcp-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: compass-manager-role
subjects:
- kind: ServiceAccount
  name: compass-manager
  namespace: kcp-system