apiVersion: operator.kyma-project.io/v1beta1
kind: CompassManager
metadata:
  labels:
    app.kubernetes.io/name: compassmanager
    app.kubernetes.io/instance: compassmanager-sample
    app.kubernetes.io/part-of: compass-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: compass-manager
  name: compassmanager-sample
spec:
  # TODO(user): Add fields here
