name: Compass Manager tests

on:
  pull_request:
    paths-ignore:
    - '.**'
    - 'docs/**'
    - '**.md'
    - 'sec-scanners-config.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      working-directory: compass-manager
    steps:
    - uses: actions/checkout@v3

    - name: Set up Golang
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.21'

    - name: Run the tests
      run: make test
