# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy-scan

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: Build
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: 1
          format: table
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          timeout: 5m0s
          vulnerability:
            ignore-unfixed: false
            type: os,library
          scan:
            scanners:
              - vuln
              - secret
          db:
            no-progress: true
